In [1]:
import os
import sys
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Layer, Dense
from tensorflow.keras.optimizers import Adam
import tensorflow_probability as tfp
from vocab import Vocabulary
from env import ConceptData
from create_data import addFile
import tensorflow as tf
import random
import numpy as np
import csv
import re
import os
import create_data
from xml.dom import minidom
import xml.etree.ElementTree as ET
from vocab import Vocabulary
from env2 import ConceptData
from create_data import addFile
import agents
import sender

In [2]:
sender_encoder = sender.Sender(num_options=10, batch_size=32)
sender_only_target = sender.SenderOnlyTarget(batch_size=32)
sender = sender.Sender_LSTM(vocab_size=99, embed_dim=44, num_cells=1, hidden_size=1, max_len=10, see_all_input=True)

In [3]:
vocabulary = Vocabulary()

def addFile(name):
    file_name = name + "_structured_final.xml"
    file = minidom.parse(os.path.join(os.path.join('visa_dataset', 'UK'), file_name))
    concepts = file.getElementsByTagName('concept')

    for concept in concepts:
        vocabulary.addConcept(concept)


addFile("ANIMALS")
addFile("APPLIANCES")
addFile("ARTEFACTS")
addFile("CLOTHING")
addFile("CONTAINER")
addFile("DEVICE")
addFile("FOOD")
addFile("HOME")
addFile("INSTRUMENTS")
addFile("MATERIAL")
addFile("PLANTS")
addFile("STRUCTURES")
addFile("TOOLS")
addFile("TOYS")
addFile("VEHICLES")
addFile("WEAPONS")

for concept in vocabulary.concept_list:
    vocabulary.parseConcept(concept)
    
data = ConceptData(vocabulary, 9, 32)

In [4]:
sender_input, targets, receiver_input = data.getInput()
#print(sender_input.shape)

shape sender input:
(32, 10, 1, 595)


In [6]:
sender_encoded = sender_encoder(sender_input)
message, logits, entropy, state_h = sender(sender_encoded)
print("message:")
print(message)
print("logits:")
print(logits)
print("entropy:")
print(entropy)
print("state_h:")
print(state_h)

32
input-shape:
(32, 10, 44)
message:
tf.Tensor(
[[37 74 85 63  8 16 36 28  9  0  0  0  0  0  0  0  0  0]
 [ 1 29 84 69 85 84 18 69 42  0  0  0  0  0  0  0  0  0]
 [87 92 77 82 54 74 38 65 41  0  0  0  0  0  0  0  0  0]
 [69 28 67 48 51 21 38 37 58  0  0  0  0  0  0  0  0  0]
 [47 94 88 81 32 98 24  0 44  0  0  0  0  0  0  0  0  0]
 [22 34 39 34 64  3 52 68 85  0  0  0  0  0  0  0  0  0]
 [77 75 81 79 60 41 97  5  6  0  0  0  0  0  0  0  0  0]
 [43 38 43 54  4 15 16 91 10  0  0  0  0  0  0  0  0  0]
 [48 59 68 20 27 33 23 55 76  0  0  0  0  0  0  0  0  0]
 [55 70 92 17 51 16 27 43 64  0  0  0  0  0  0  0  0  0]
 [92 51 85 96 42 11 84 42 58  0  0  0  0  0  0  0  0  0]
 [26 46 58 93 93 44  2  8 98  0  0  0  0  0  0  0  0  0]
 [82 14 96 74 61 49 46 80 80  0  0  0  0  0  0  0  0  0]
 [57 88 95 26 85 33 69 76 25  0  0  0  0  0  0  0  0  0]
 [94 89 55 65 97 68 44 57 46  0  0  0  0  0  0  0  0  0]
 [85 95 18 22 30 18 89 36 14  0  0  0  0  0  0  0  0  0]
 [ 3 65 34 29 52 82  9 91 41  0  0  0  