In [1]:
import os
import sys
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Layer, Dense
from tensorflow.keras.optimizers import Adam
import tensorflow_probability as tfp
from vocab import Vocabulary
from env2 import ConceptData
from create_data import addFile
import tensorflow as tf
import random
import numpy as np
import csv
import re
import os
import create_data
from xml.dom import minidom
import xml.etree.ElementTree as ET
import agents
import sender2
import game2
from agents import find_lengths

In [2]:
NUM_OPTIONS = 10
NUM_DISTRACTORS = 9
BATCH_SIZE = 32
HIDDEN_SIZE = 44
EMBED_DIM = 44
VOCAB_SIZE = 99
MAX_LEN = 10
NUM_EPOCHS = 5
TRAINING = True
SENDER_ALL_INPUT = True
sender_entropy_coeff = 0.015 #wie bei Ossenkopf
receiver_entropy_coeff = 0.0 # wie bei Ossenkopf


In [3]:

vocabulary = Vocabulary()

def addFile(name):
    file_name = name + "_structured_final.xml"
    file = minidom.parse(os.path.join(os.path.join('visa_dataset', 'UK'), file_name))
    concepts = file.getElementsByTagName('concept')

    for concept in concepts:
        vocabulary.addConcept(concept)


addFile("ANIMALS")
addFile("APPLIANCES")
addFile("ARTEFACTS")
addFile("CLOTHING")
addFile("CONTAINER")
addFile("DEVICE")
addFile("FOOD")
addFile("HOME")
addFile("INSTRUMENTS")
addFile("MATERIAL")
addFile("PLANTS")
addFile("STRUCTURES")
addFile("TOOLS")
addFile("TOYS")
addFile("VEHICLES")
addFile("WEAPONS")

for concept in vocabulary.concept_list:
    vocabulary.parseConcept(concept)

In [4]:
#Initialisiere die Agents
sender_encoder = sender2.Sender(num_options=NUM_OPTIONS, batch_size=BATCH_SIZE)
sender_LSTM = sender2.Sender_LSTM(agent = sender_encoder,
                                    embed_dim=EMBED_DIM,
                                    num_cells=1,
                                    hidden_size=1, 
                                    max_len=MAX_LEN,
                                see_all_input=SENDER_ALL_INPUT)
receiver_encoder = agents.Receiver(num_options = NUM_OPTIONS)
receiver_LSTM = agents.Receiver_LSTM(agent=receiver_encoder, 
                                       vocab_size=VOCAB_SIZE,
                                       embed_dim=EMBED_DIM, 
                                       hidden_size=HIDDEN_SIZE)
guesser = agents.AuxiliaryNetwork(hidden_size=HIDDEN_SIZE)


In [5]:
#the losses

#loss of guessing the correct target
def loss(_sender_input, _message, _receiver_input, input_concepts, receiver_output, targets):
    """
    receiver_output ist was von receiver_sampling zurückgegeben wird
    LABELS PRINTEN IN OSSSENKOPF NOTEBOOK
    """
    guesses = []
    
    for i in range(len(receiver_output)):
        guesses.append(input_concepts[i][receiver_output[i]])
            
    guesses = tf.convert_to_tensor(guesses)
    targets = tf.convert_to_tensor(targets)
    acc = np.sum(guesses == targets) / guesses.shape[0]
    #acc = np.sum(guesses == targets) - np.sum(guesses != targets)
        
    return -acc

#auxiliary loss to promote empathy
def auxiliary_loss(receiver_thoughts, 
                  # _message, _receiver_input, 
                   guesser_output, 
                   #_labels,
                   weight=0.2):
    mae = tf.keras.losses.MeanAbsoluteError(reduction = 'none')
    loss = mae(receiver_thoughts, guesser_output)
    loss *= weight
    
    return loss

In [6]:
game = game2.Game(sender_encoder=sender_encoder,
                  sender=sender_LSTM,
                receiver=receiver_LSTM,
                main_loss=loss,
                sender_entr_coeff=sender_entropy_coeff,
                receiver_entr_coeff=receiver_entropy_coeff,
                batch_size=BATCH_SIZE,
                max_len=MAX_LEN,
                 sender_all_input=SENDER_ALL_INPUT)

In [7]:
optim_guesser = tf.keras.optimizers.Adam(learning_rate = 1e-3)
optim_receiver = tf.keras.optimizers.Adam(learning_rate = 1e-2)
optim_sender = tf.keras.optimizers.Adam(learning_rate = 1e-3)
#optim_game = tf.keras.optimizers.Adam(learning_rate = 1e-5)

In [8]:
losses_network = []
losses_aux = []

for i in range(NUM_EPOCHS):
    
    data = ConceptData(voc=vocabulary, num_distractors=NUM_DISTRACTORS, batch_size=BATCH_SIZE)
    input_concepts, sender_input, targets, receiver_input = data.getInput()
    
    
    with tf.GradientTape(persistent=True) as tape:
        
        loss, prev_hidden, last_hidden, acc, message = game(input_concepts, sender_input, targets, receiver_input)
        losses_network.append(np.mean(loss))
        receiver_gradients = tape.gradient(loss, game.receiver.trainable_variables)
        print("Receiver_Gradients: ")
        print(receiver_gradients)
        print('_____________________________________________________________')
        sender_lstm_gradients = tape.gradient(loss, game.sender.trainable_variables)
        print('Sender_LSTM_Gradients: ')
        print(sender_lstm_gradients)
        print('_____________________________________________________________')
        sender_encoder_gradients = tape.gradient(loss, game.sender_encoder.trainable_variables)
        print('Sender_Encoder_Gradients: ')
        print(sender_encoder_gradients)
        print('_____________________________________________________________')

    optim_receiver.apply_gradients(zip(receiver_gradients, game.receiver.trainable_variables))
    optim_sender.apply_gradients(zip(sender_lstm_gradients, game.sender.trainable_variables))
    
    with tf.GradientTape() as tape:
        
        guesser_output = guesser(prev_hidden)
        aux_loss = auxiliary_loss(last_hidden, guesser_output)
        losses_aux.append(aux_loss)
        aux_loss_mean = np.mean(aux_loss)
        
        aux_gradients = tape.gradient(aux_loss, guesser.trainable_variables)
        
        # add gradients of guesser onto gradients of sender_encoder to update sender_encoder with these
        #sender_encoder_grad_all = []
        #for i in range(len(aux_gradients)):
            #sender_encoder_grad_all.append(aux_gradients[i] + sender_encoder_gradients[i])
        
    optim_guesser.apply_gradients(zip(aux_gradients, guesser.trainable_variables))
    #optim_sender.apply_gradients(zip(sender_encoder_grad_all, game.sender_encoder.trainable_variables))
    print(f'epoch::: {i}   loss::: {np.mean(loss)}   acc::: {acc}   aux_loss::: {aux_loss_mean}')
        

Receiver_Gradients: 
[<tf.Tensor: shape=(595, 44), dtype=float32, numpy=
array([[-6.1779644e-04,  1.5259060e-04, -4.1328566e-04, ...,
         1.1298083e-03, -5.0625857e-04, -7.5530540e-04],
       [-6.4476248e-05, -8.7125391e-06, -3.9207545e-05, ...,
         1.1605015e-04, -4.3182568e-05, -5.6411038e-05],
       [-3.5140413e-04,  3.3492255e-05, -3.0315627e-04, ...,
         7.8415388e-04, -4.3299765e-04, -4.5476141e-04],
       ...,
       [ 2.0307676e-04, -3.0125218e-05,  1.6455911e-04, ...,
        -3.9061290e-04,  2.1059121e-04,  2.4883324e-04],
       [ 2.0307676e-04, -3.0125218e-05,  1.6455911e-04, ...,
        -3.9061290e-04,  2.1059121e-04,  2.4883324e-04],
       [ 2.0307676e-04, -3.0125218e-05,  1.6455911e-04, ...,
        -3.9061290e-04,  2.1059121e-04,  2.4883324e-04]], dtype=float32)>, <tf.Tensor: shape=(44,), dtype=float32, numpy=
array([ 7.5150456e-07, -2.2705572e-06,  1.1830562e-06,  1.0643547e-05,
        2.4145418e-05,  3.2290991e-06, -1.2382239e-05, -9.1318907e-07,


ValueError: No gradients provided for any variable: ['game/sender/sender_encoder/dense/kernel:0', 'game/sender/sender_encoder/dense/bias:0', 'game/sender_lstm/dense_1/kernel:0', 'game/sender_lstm/dense_1/bias:0', 'game/sender_lstm/lstm/lstm_cell/kernel:0', 'game/sender_lstm/lstm/lstm_cell/recurrent_kernel:0', 'game/sender_lstm/lstm/lstm_cell/bias:0', 'game/sender_lstm/lstm_1/lstm_cell_1/kernel:0', 'game/sender_lstm/lstm_1/lstm_cell_1/recurrent_kernel:0', 'game/sender_lstm/lstm_1/lstm_cell_1/bias:0'].

In [ ]:
losses_network